-- One-call admin hard delete for users + dependent profile/business data.
-- Usage (dry run):  select public.admin_delete_user('<user-uuid>', true);
-- Usage (delete):   select public.admin_delete_user('<user-uuid>', false);

create schema if not exists private;

revoke all on schema private from public;
grant usage on schema private to service_role;

create table if not exists private.user_deletion_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  requested_by uuid,
  dry_run boolean not null default false,
  result jsonb not null,
  created_at timestamptz not null default now()
);

comment on table private.user_deletion_audit is
  'Audit trail for admin user deletion requests (dry-run + hard delete).';

create or replace function private.delete_user_cascade(
  p_user_id uuid,
  p_dry_run boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, private, pg_temp
as $$
declare
  v_profile_row public.profiles%rowtype;
  v_auth_email text;
  v_counts jsonb;
  v_result jsonb;
  v_has_profile boolean := false;
  v_has_auth boolean := false;
  v_has_owned_businesses boolean := false;
  v_has_candidate_profile boolean := false;
begin
  if p_user_id is null then
    raise exception 'p_user_id is required';
  end if;

  select *
  into v_profile_row
  from public.profiles
  where id = p_user_id;

  v_has_profile := found;

  select u.email
  into v_auth_email
  from auth.users u
  where u.id = p_user_id;

  v_has_auth := found;

  select exists (
    select 1 from public.businesses b where b.owner_id = p_user_id
  )
  into v_has_owned_businesses;

  select exists (
    select 1 from public.candidate_profiles cp where cp.user_id = p_user_id
  )
  into v_has_candidate_profile;

  if not v_has_profile
     and not v_has_auth
     and not v_has_owned_businesses
     and not v_has_candidate_profile then
    v_result := jsonb_build_object(
      'user_id', p_user_id,
      'dry_run', p_dry_run,
      'already_deleted', true,
      'message', 'No profile, auth user, or dependent rows found. User appears already deleted.'
    );

    if not p_dry_run then
      insert into private.user_deletion_audit (user_id, requested_by, dry_run, result)
      values (p_user_id, auth.uid(), false, v_result);
    end if;

    return v_result;
  end if;

  v_counts := jsonb_build_object(
    'candidate_profiles',
      (select count(*) from public.candidate_profiles cp where cp.user_id = p_user_id),
    'businesses',
      (select count(*) from public.businesses b where b.owner_id = p_user_id),
    'roles',
      (
        select count(*)
        from public.roles r
        where r.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
      ),
    'employer_trait_weightings',
      (
        select count(*)
        from public.employer_trait_weightings etw
        where etw.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
      ),
    'explore_role_interest_employer_notifications',
      (
        select count(*)
        from public.explore_role_interest_employer_notifications n
        where n.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
           or n.candidate_id in (select cp.id from public.candidate_profiles cp where cp.user_id = p_user_id)
      ),
    'engagements',
      (
        select count(*)
        from public.engagements e
        where e.candidate_id in (select cp.id from public.candidate_profiles cp where cp.user_id = p_user_id)
           or e.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
      ),
    'hiring_decisions',
      (
        select count(*)
        from public.hiring_decisions hd
        where hd.engagement_id in (
          select e.id
          from public.engagements e
          where e.candidate_id in (select cp.id from public.candidate_profiles cp where cp.user_id = p_user_id)
             or e.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
        )
      ),
    'performance_snapshots',
      (
        select count(*)
        from public.performance_snapshots ps
        where ps.engagement_id in (
          select e.id
          from public.engagements e
          where e.candidate_id in (select cp.id from public.candidate_profiles cp where cp.user_id = p_user_id)
             or e.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
        )
           or ps.hiring_decision_id in (
             select hd.id
             from public.hiring_decisions hd
             where hd.engagement_id in (
               select e.id
               from public.engagements e
               where e.candidate_id in (select cp.id from public.candidate_profiles cp where cp.user_id = p_user_id)
                  or e.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
             )
           )
      )
  );

  v_result := jsonb_build_object(
    'user_id', p_user_id,
    'email', coalesce(v_profile_row.email, v_auth_email),
    'role', v_profile_row.role,
    'dry_run', p_dry_run,
    'counts', v_counts
  );

  if p_dry_run then
    insert into private.user_deletion_audit (user_id, requested_by, dry_run, result)
    values (p_user_id, auth.uid(), true, v_result);

    return v_result;
  end if;

  -- Delete in dependency-safe order (employer businesses included).
  delete from public.performance_snapshots
  where engagement_id in (
    select e.id
    from public.engagements e
    where e.candidate_id in (select cp.id from public.candidate_profiles cp where cp.user_id = p_user_id)
       or e.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
  )
     or hiring_decision_id in (
       select hd.id
       from public.hiring_decisions hd
       where hd.engagement_id in (
         select e.id
         from public.engagements e
         where e.candidate_id in (select cp.id from public.candidate_profiles cp where cp.user_id = p_user_id)
            or e.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
       )
     );

  delete from public.hiring_decisions
  where engagement_id in (
    select e.id
    from public.engagements e
    where e.candidate_id in (select cp.id from public.candidate_profiles cp where cp.user_id = p_user_id)
       or e.business_id in (select b.id from public.businesses b where b.owner_id = p_user_id)
  );

  delete from public.engagements
  where candidate_id in (select cp.id from public.candidate_profiles cp where cp.user_id = p_user_id)
     or business_id in (select b.id from public.businesses b where b.owner_id = p_user_id);

  delete from public.employer_trait_weightings
  where business_id in (select b.id from public.businesses b where b.owner_id = p_user_id);

  delete from public.roles
  where business_id in (select b.id from public.businesses b where b.owner_id = p_user_id);

  delete from public.businesses
  where owner_id = p_user_id;

  delete from public.candidate_profiles
  where user_id = p_user_id;

  delete from public.profiles
  where id = p_user_id;

  delete from auth.identities
  where user_id = p_user_id;

  delete from auth.users
  where id = p_user_id;

  v_result := v_result || jsonb_build_object('deleted', true);

  insert into private.user_deletion_audit (user_id, requested_by, dry_run, result)
  values (p_user_id, auth.uid(), false, v_result);

  return v_result;
end;
$$;

revoke all on function private.delete_user_cascade(uuid, boolean) from public, anon, authenticated;
grant execute on function private.delete_user_cascade(uuid, boolean) to service_role;

create or replace function public.admin_delete_user(
  p_user_id uuid,
  p_dry_run boolean default false
)
returns jsonb
language sql
security invoker
set search_path = public, private
as $$
  select private.delete_user_cascade(p_user_id, p_dry_run);
$$;

comment on function public.admin_delete_user(uuid, boolean) is
  'Admin-only helper to dry-run or hard-delete a user, employer businesses, and dependent rows.';

revoke all on function public.admin_delete_user(uuid, boolean) from public, anon, authenticated;
grant execute on function public.admin_delete_user(uuid, boolean) to service_role;
